### ISSUE TITLE
[Bug] CMake Error: Version deprecation

### ISSUE THREAD

**Issue by v3rm1n0** [vicinaehq/vicinae#450]
> [!WARNING]  
> If you are able to run Vicinae on your system, you should use the "Report bug" command to create a new issue as it will auto fill version and system information for you (since v0.6.1).
> You can automatically run it using:
> ```vicinae vicinae://extensions/vicinae/vicinae/report-bug```

## **System information**

NixOS Unstable

## **Describe the bug**
Building vicinae from the latest hash (b3a3f45aba1738c540c13d7b0bdddf3fb771376a) results in a build error:

```txt
cmark-gfm> CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
cmark-gfm>   Compatibility with CMake < 3.5 has been removed from CMake.
cmark-gfm>
cmark-gfm>   Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
cmark-gfm>   to tell CMake that the project requires at least <min> but has been updated
cmark-gfm>   to work with policies introduced by <max> or earlier.
cmark-gfm>
cmark-gfm>   Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
cmark-gfm>
cmark-gfm>
cmark-gfm> -- Configuring incomplete, errors occurred!
```

https://github.com/vicinaehq/vicinae/actions/runs/18329686570/job/52202148667

The job for cachix seemed to have failed to

**Comment by aurelleb** [comment]
https://github.com/vicinaehq/vicinae/pull/445#issuecomment-3379286238

No idea if there is something I can do to fix this on my end, as this is a bug that occurs when building one of the dependencies, not vicinae itself. According to the explanation linked above we have to wait for a nix update?

**Comment by v3rm1n0** [comment]
I’ll keep an eye on it, but thanks for your work 🫡

**Comment by whispersofthedawn** [comment]
Yep! The two failing dependencies are cmark-gfm (nixos/nixpkgs#449569) and grpc-tools (nixos/nixpkgs#449946). The first one I mentioned in that comment, but I also uncovered the second one after compiling with the first. I put up a nixpkgs PR to fix the grpc-tools failure, and after applying both of those fixes, I can successfully build vicinae on my machine. That means we'll have to wait for the second PR to be merged and then make its way to nixos-unstable as well.

**Comment by pyrox0** [comment]
Merged 🫡 as a vicinae user and nixpkgs commiter im glad to help support it from the nixpkgs deps side lol

**Comment by v3rm1n0** [comment]
@pyrox0 both seem to be on unstable now but i still get errors. This is not the actual thread for this kind of issue but I thought Id share nevertheless 

```txt
unning phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/n2dxlasw5fahy3p6d6m780pbdc98fw43-source
source root is source
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
cmake flags: -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_LOCALEDIR=/nix/store/jg0hpzyhr9ym31f2adm84c0xvh1j41m2-cma>
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 has been removed from CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.

  Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.


-- Configuring incomplete, errors occurred!
```

**Comment by pyrox0** [comment]
If you are using the unmodified flake, then you will not have either fix yet, as neither have landed in the branch that this repo's flake.nix uses(`nixos-unstable`, per https://github.com/vicinaehq/vicinae/blob/7757b8fc6ee8488a8cb27aca3260317132676540/flake.nix#L5f). Also, once the fixes do land in the branch, unless you are overriding it in your own flake, you will need to wait for the flake here to be updated to a commit that has those fixes landed.

I've confirmed that overriding the input in my own flake makes it build properly, so now it's a matter of waiting for these fixes to land in the nixos-unstable channel.

See the following pages for the status of the relevant PRs:
[`#449569`](https://nixpkgs-tracker.ocfox.me/?pr=449569)
[`#449946`](https://nixpkgs-tracker.ocfox.me/?pr=449946)

**Comment by schromp** [comment]
shouldnt the nixpkgs-unstable branch be enough?
both are already in there

EDIT: nevermind sorry, the github action seems to depend on nixos-unstable

**Comment by v3rm1n0** [comment]
dumb question maybe, but why? Is there any advantage of choosing nixos-unstable over nixpkgs-unstable? Does the project use any nixos modules?

**Comment by schromp** [comment]
> dumb question maybe, but why? Is there any advantage of choosing nixos-unstable over nixpkgs-unstable? Does the project use any nixos modules?


I removed it in #465.

However we still have another error which we will have to fix:
```
 > CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
       >   Compatibility with CMake < 3.5 has been removed from CMake.
       >
       >   Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
       >   to tell CMake that the project requires at least <min> but has been updated
       >   to work with policies introduced by <max> or earlier.
       >
       >   Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
```

This is because some of the CMakeLists.txt files still have `cmake_minimum_required(VERSION 3.16)`.
Im guessing we can fix this on the nix side instead of changing that in the whole project though.

**Comment by v3rm1n0** [comment]
> This is because some of the CMakeLists.txt files still have `cmake_minimum_required(VERSION 3.16)`.
> Im guessing we can fix this on the nix side instead of changing that in the whole project though.

https://github.com/vicinaehq/vicinae/blob/main/CMakeLists.txt
https://github.com/vicinaehq/vicinae/blob/main/lib/xdgpp/CMakeLists.txt

Those seem to be the two files

**Comment by whispersofthedawn** [comment]
> This is because some of the CMakeLists.txt files still have `cmake_minimum_required(VERSION 3.16)`.
> Im guessing we can fix this on the nix side instead of changing that in the whole project though.

Nope, 3.16 is 100% fine. This error that you're seeing is in a dependency of vicinae, not vicinae itself (unless a new issue has surfaced, which would be surprising); above the snippet you've given, there's likely a line like:
```
error: builder for '/nix/store/yzn5yjad6bxvmnf725wmx9aim9wh8f80-cmark-gfm-0.29.0.gfm.13.drv' failed with exit code 1;
```
or a similar line with the words `grpc-tools` in it. These are dependencies, and as pyrox said above, these are already fixed on nixpkgs master. In fact, the hydra build containing these fixes already passed nine hours ago (https://hydra.nixos.org/job/nixos/trunk-combined/tested), so once all of the packages are uploaded to the https://cache.nixos.org CDN (and maybe some other steps? regardless, should only take a few more hours), the `nixos-unstable` branch will be updated. If you want these changes faster, you can point your nixpkgs at commit 0b4defa2584313f3b781240b29d61f6f9f7e0df3 ([link](https://github.com/NixOS/nixpkgs/tree/0b4defa2584313f3b781240b29d61f6f9f7e0df3)) and you can go straight there. (If you're using flakes, you can do that override temporarily with `nix flake lock --override-input nixpkgs github:NixOS/nixpkgs/0b4defa2584313f3b781240b29d61f6f9f7e0df3` I *think*.)

**Comment by aurelleb** [comment]
yeah that's a dependency problem. `grpc-tools` has it and `cmark` also has it. Binary releases are linked to cmark statically and I have to use a special cmake option to ignore it https://github.com/vicinaehq/vicinae/blob/4d6d3e6e972e17d271ddb607ade9ff7106a721e0/.github/workflows/release.yml#L64

**Comment by schromp** [comment]
ah yes i understand the error better now.
it came up while building my local devshell, which of course depends on nixos-unstable. Thats why the build works but the devshell doesnt.
Sorry for the confusion :)

**Comment by v3rm1n0** [comment]
Builds again 👍
